name: 'Synopsys Detect'
description: 'Runs Detect script to find out vulnerabilities.'
author: 'Gautam Baghel @ Synopsys'
inputs:
  myInput:
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'index.js'
