name: 'Synopsys Detect'
description: 'Runs Detect script to find out vulnerabilities.'
author: 'Gautam Baghel @ Synopsys'
inputs:
  args:
    description: 'Synopsys Detect arguments'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
