name: Action Self Check
on: push
jobs:
  build
    name: Build & Detect
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Polaris
        uses: ./
        with:
          args: '--polaris.url="${{ secrets.POLARIS_URL}}" --polaris.access.token="${{ secrets.POLARIS_TOKEN}}" --detect.tools="POLARIS"'
      - name: Synopsys Detect
        uses: ./
        with:
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true'
      - uses: actions/upload-artifact@master
        with:
          name: synopsys-detect-report
          path: gautambaghel_synopsys_detect_js_HEAD_BlackDuck_RiskReport.pdf
