name: Detect JS Tests
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    # Job name is Greeting
    name: Build & Detect
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Polaris
        uses: ./
        with:
          args: '--polaris.url="${{ secrets.POLARIS_URL}}" --polaris.access.token="${{ secrets.POLARIS_TOKEN}}" --detect.tools="POLARIS"'
      - name: Synopsys Detect
        uses: ./
        with:
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true'
      - uses: actions/upload-artifact@master
        with:
          name: synopsys-detect-report
          path: gautambaghel_synopsys_detect_js_HEAD_BlackDuck_RiskReport.pdf
